# Generated by Django 6.0 on 2026-01-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_animal', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ACTIVO', max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique='True')),
                ('tipo', models.CharField(choices=[('VACUNA', 'Vacuna'), ('TRATAMIENTO', 'Tratamiento')], max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('volver_a_suministrar_dias', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_animal', to='gestion_sanitaria.animal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_suministros', to='gestion_sanitaria.productosanitario')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('animal', 'producto', 'fecha')},
            },
        ),
    ]
