# Generated by Django 6.0 on 2026-01-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sanitaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosanitario',
            old_name='stock',
            new_name='unidades_disponibles',
        ),
    ]
