# Generated by Django 6.0 on 2026-01-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sanitaria', '0002_rename_stock_productosanitario_unidades_disponibles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialsanitario',
            options={'ordering': ['-fecha_suministro']},
        ),
        migrations.RenameField(
            model_name='historialsanitario',
            old_name='fecha',
            new_name='fecha_suministro',
        ),
        migrations.AlterUniqueTogether(
            name='historialsanitario',
            unique_together={('animal', 'producto', 'fecha_suministro')},
        ),
    ]
