# Generated by Django 6.0 on 2026-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_sanitaria', '0003_alter_historialsanitario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosanitario',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
